config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :products

  resources :users, only: [:edit, :update, :show]

  get 'pages/landing_page'

  get 'pages/contact'

  get 'pages/about'

  get 'form_input',   to: 'form_example#form_input'
  post 'form_output',  to: 'form_example#form_output'

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end

end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    
    #   can :update, Article, :published => true
    
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    # return the path based on resource
    products_path
  end
 end

app/controllers/form_example_controller.rb
class FormExampleController < ApplicationController
  def form_input
  end

  def form_output
	  @name = params[:name]
	  @email = params[:email]
	  @message = params[:message]
	  render "form_result"
  	ActionMailer::Base.mail(:from => 'no-reply@example.com', 
	  	:to => @email, 
	  	:subject => "A new contact form message", 
	  	:body => @message).deliver
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing_page
  end

  def contact
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_ural, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  load_and_authorize_resource

  def show
  end

  def edit
  end

  def update
    @user.update_attributes(user_params)
  end

  private

  def user_params
    require(:user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/form_example/form_input.html.erb
<h1> Form input </h1>
<%= form_tag(form_output_path) do %>
    <div>
        <%= label_tag 'name', 'Name' %>
        <%= text_field_tag 'name', nil, placeholder: 'Your Name' %>
    </div>
   <div>
       <%= label_tag 'email', 'Email' %>
       <%= email_field_tag 'email', nil, placeholder: 'Your Email Address' %>
   </div>
   <div>
       <%= label_tag 'message', 'message' %>
       <%= text_area_tag 'message', nil, rows: 4, placeholder: 'Message...' %>
   </div>
   <%= submit_tag "Submit" %>
<% end %>

app/views/form_example/form_result.html.erb
<p>Your message has been submitted:</p>
<p>Name: <%= @name %></p>
<p>Email: <%= @email %></p>
<p>Message: <%= @message %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wunderclass</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
<img src="http://localhost:3000/images/bestway.jpg"
</head>
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
<body>
	<h1>WunderClass</h1>
<nav>
<ul>
<!-- <li><a href="/pages/landing_page">Home</a></li> -->
<li><%= link_to "Home", "/pages/landing_page" %></li>
<li><a href="/pages/about">About</a></li>
<li><a href="/pages/contact">Contact</a></li>
<li><%= link_to 'All Products', products_path %></li>
 <% if user_signed_in? %>
  <li>You are logged in as <%= current_user.email %></li>
  <li><%= link_to 'log out', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to "Sign Up", new_user_registration_path %></li>
  <li><%= link_to "Sign In", new_user_session_path %></li>
<% end %>
</ul>
</nav>
<!--flash notification-->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
 <!--end flash notification-->

 <%= yield %>
</body>
</html>

app/views/pages/_featured_product.html.erb
<h1>Product Example</h1>

app/views/pages/about.html.erb
<h1>A digital transformation is coming. Are you ready?</h1>
<p>We believe it's not the tools we have, but how we learn to use it. Technology is more than just smartboards and computers. </p>
<p>
<p>WunderClass cuts down on your mark making, grading, and classroom administration by 35%, so you have more time to focus on the most important part of your job - your students.</p>

app/views/pages/contact.html.erb
<h1>Made for teachers, by teachers.</h1>
<h2>Meet our team below</h2>

app/views/pages/landing_page.html.erb
<p>We know that teaching is one of the most difficult jobs in the world.</p>
That's why we designed a tool to save time, stay organized, and make your life easier.
<h1>Welcome to the future of classroom management.</h1>
<h2>Made for teachers, By teachers.</h2>
<p>Coming soon! Sign up for the latest updates now.</p>
<%= render 'featured_product' %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_ural %><br>
    <%= f.text_field :image_ural %>
  </div>
    <div class="field">
    <%= f.label :inventorynumber %><br>
    <%= f.text_field :inventorynumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Inventory Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_ural %></td>
        <td><%= product.price %></td>
        <td><%= product.inventorynumber %></td>

        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image ural:</strong>
  <%= @product.image_ural %>
</p>

<p>
	<strong>Price:</strong>
  	<%= @product.price %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- add Product Edit code -->

app/views/users/show.html.erb
 <!-- Display user data -->
<!-- # Copy what's in product views
 Change variable to user
 Change attributes to user table  -->

app/views/users/update.html.erb
<!--Add form code-->

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>